name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build binary
        run: |
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o "dist/tinyups3_${GOOS}_${GOARCH}" .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tinyups3-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/tinyups3_${{ matrix.goos }}_${{ matrix.goarch }}
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Prepare release assets
        run: |
          mkdir -p release
          find dist -type f -name "tinyups3_*" -exec cp {} release/ \;

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          generate_release_notes: true
